// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEdGs-i9GxrkLeqb0q0n7-Ec2SwGgEvxI',
    appId: '1:182981659642:web:5b996efc9b10edca543243',
    messagingSenderId: '182981659642',
    projectId: 'ieee-custom-forms-181e4',
    authDomain: 'ieee-custom-forms-181e4.firebaseapp.com',
    storageBucket: 'ieee-custom-forms-181e4.appspot.com',
    measurementId: 'G-NJTMLT75G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbecEcWzlrjtj2JQdWdYskbgnd-nzRkHU',
    appId: '1:182981659642:android:ed127f5467e3cd53543243',
    messagingSenderId: '182981659642',
    projectId: 'ieee-custom-forms-181e4',
    storageBucket: 'ieee-custom-forms-181e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmg_00RBIARlTtA3FnLMpmLl_IkmQ1DSw',
    appId: '1:182981659642:ios:1282ba4e5707b5c0543243',
    messagingSenderId: '182981659642',
    projectId: 'ieee-custom-forms-181e4',
    storageBucket: 'ieee-custom-forms-181e4.appspot.com',
    iosClientId: '182981659642-7meuukenfcf4isuodcba932m8nhqj6is.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeForms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmg_00RBIARlTtA3FnLMpmLl_IkmQ1DSw',
    appId: '1:182981659642:ios:1282ba4e5707b5c0543243',
    messagingSenderId: '182981659642',
    projectId: 'ieee-custom-forms-181e4',
    storageBucket: 'ieee-custom-forms-181e4.appspot.com',
    iosClientId: '182981659642-7meuukenfcf4isuodcba932m8nhqj6is.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeForms',
  );
}
